region: $REGION
cognito:
  userPoolId: $USERPOOLID
  clientId: $APPCLIENTID
loadBalancerAddress: $ELBURL

admin:
  image: public.ecr.aws/o2b5n0j5/eks-saas-admin:latest
  port: 80
  targetPort: 80

app:
  tenantPath: app
  iamRoleArn: $IAM_ROLE_ARN

  product:
    image: public.ecr.aws/o2b5n0j5/eks-saas-product:v1.1
    productTable: $PRODUCTTABLE
    port: 80
    targetPort: 3005

  order:
    image: public.ecr.aws/o2b5n0j5/eks-saas-order:v1.1
    orderTable: $ORDERTABLE
    port: 80
    targetPort: 3010

  application:
    image: public.ecr.aws/o2b5n0j5/eks-saas-application:latest
    port: 80
    targetPort: 80
