apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: core-services-routes
spec:
  hosts:
    - "{{ .Values.loadBalancerAddress }}"
  gateways:
    - default/eks-saas-workshop-gateway
  http:
    - match:
        - uri:
            prefix: /api/registration
      route:
        - destination:
            port:
              number: 80
            host: tenant-registration-service
    - match:
        - uri:
            prefix: /api/tenants
      route:
        - destination:
            port:
              number: 80
            host: tenant-management-service
    - match:
        - uri:
            prefix: /admin
      route:
        - destination:
            port:
              number: 80
            host: admin-application-service
