region: us-west-2
eksStackName: root-stack-eksstackNestedStackeksstackNestedStackResourceE5C15B40-5MECA3FOQHYN
eksNodegroupRoleArn: arn:aws:iam::248095664621:role/root-stack-eksstackNested-CustomNodegroupRole69D93B-rpe4uRJZML3r
cognito:
  userPoolId: us-west-2_XxiuCdHh2
  clientId: qt23ssl9khoj48f9bt4shbfeh
loadBalancerAddress: 
v1v2:
  enabled: false

admin:
  image: 248095664621.dkr.ecr.us-west-2.amazonaws.com/aws-workshop/eks-saas-admin
  port: 80
  targetPort: 80
  
core:
  tenantTableName: 
  authInfoTableName: 
  tenantStackMappingTable: 

  tenantManagement:
    image: 248095664621.dkr.ecr.us-west-2.amazonaws.com/aws-workshop/eks-saas-tenant-management
    port: 80
    targetPort: 3001
    
  tenantRegistration:
    image: 248095664621.dkr.ecr.us-west-2.amazonaws.com/aws-workshop/eks-saas-tenant-registration
    name: tenant-registration
    port: 80
    targetPort: 3000
    
  userManagement:
    image: 248095664621.dkr.ecr.us-west-2.amazonaws.com/aws-workshop/eks-saas-user
    name: user-management
    port: 80
    targetPort: 3015
    
app:
  tenantPath: app
  iamRoleArn: arn:aws:iam::248095664621:role/root-stack-eksstackNested-DynamicAssumeRole644B86FF-c0kXtIDxuQxg
  
  product:
    image: 248095664621.dkr.ecr.us-west-2.amazonaws.com/aws-workshop/eks-saas-product
    productTable: Products-Pooled
    port: 80
    targetPort: 3005
    
  order:
    image: 248095664621.dkr.ecr.us-west-2.amazonaws.com/aws-workshop/eks-saas-order:v1
    imagev2: 248095664621.dkr.ecr.us-west-2.amazonaws.com/aws-workshop/eks-saas-order:v2
    orderTable: Orders-Pooled
    port: 80
    targetPort: 3010
  
  application:
    image: 248095664621.dkr.ecr.us-west-2.amazonaws.com/aws-workshop/eks-saas-application
    port: 80
    targetPort: 80
