version: 0.2

env:
  variables:
    VPC_ID: VPC_ID_NOT_SET
    CLOUD9_ENVIRONMENT_ID: CLOUD9_ENVIRONMENT_ID_NOT_SET
    CFN_RESPONSE_URL: CFN_RESPONSE_URL_NOT_SET
    CFN_STACK_ID: CFN_STACK_ID_NOT_SET
    CFN_REQUEST_ID: CFN_REQUEST_ID_NOT_SET
    CFN_LOGICAL_RESOURCE_ID: CFN_LOGICAL_RESOURCE_ID_NOT_SET

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 18
    commands:
      - cd $CODEBUILD_SRC_DIR/cdk/workshop
      - npm install
  pre_build:
    on-failure: ABORT
    commands:
      - cd $CODEBUILD_SRC_DIR/cdk/workshop
      - npm run build
      - "export AWS_ACCOUNT_ID=$(echo $CODEBUILD_BUILD_ARN | cut -d: -f5)"
      - 'echo "AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID"'
      - npx cdk bootstrap aws://$AWS_ACCOUNT_ID/$AWS_REGION
  build:
    on-failure: ABORT
    commands:
      - cd $CODEBUILD_SRC_DIR/cdk/workshop
      - "export AWS_ACCOUNT_ID=$(echo $CODEBUILD_BUILD_ARN | cut -d: -f5)"
      - 'echo "AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID"'
      - 'echo "VPC ID: $VPC_ID"'
      - 'echo "CLOUD9_ENVIRONMENT_ID: $CLOUD9_ENVIRONMENT_ID"'
      - 'echo "WS_PARTICIPANT_ROLE_ARN: $WS_PARTICIPANT_ROLE_ARN"'
      - npx cdk deploy root-stack --require-approval never --no-rollback
