apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{.Values.app.tenantPath}}
spec:
  template:
    metadata:
      labels:
        node-pool: {{.Values.app.tenantPath}}
    spec:
      nodeClassRef:
        kind: EC2NodeClass
        name: {{.Values.app.tenantPath}}
      taints:
        - key: node-pool
          value: {{.Values.app.tenantPath}}
          effect: NoSchedule
  limits:
    cpu: "100"
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: {{.Values.app.tenantPath}}
spec:
  subnetSelectorTerms:
    - tags:
        "aws:cloudformation:stack-name": {{ .Values.eksStackName }}
  securityGroupSelectorTerms:
    - tags:
        "aws:eks:cluster-name": "eksworkshop-eksctl"
  tags:
    "karpenter.sh/discovery": "eksworkshop-eksctl"      