---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-routes
spec:
  hosts:
    - "{{ .Values.loadBalancerAddress }}"
  gateways:
    - default/eks-saas-workshop-gateway
  http:
    - match:
        - uri:
            prefix: /{{.Values.app.tenantPath}}/products/metrics
      route:
        - destination:
            port:
              number: 80
            host: product-service
    - match:
        - uri:
            prefix: /{{.Values.app.tenantPath}}/api/products
      route:
        - destination:
            port:
              number: 80
            host: product-service
    - match:
        - uri:
            prefix: /{{.Values.app.tenantPath}}/orders/metrics
      route:
        - destination:
            port:
              number: 80
            host: order-service
    - match:
        - uri:
            prefix: /{{.Values.app.tenantPath}}/api/orders
      route:
        - destination:
            port:
              number: 80
            host: order-service
    - match:
        - uri:
            prefix: /{{.Values.app.tenantPath}}
      route:
        - destination:
            port:
              number: 80
            host: application-service
