apiVersion: v1
data:
  config.json: |
    {
      "apiUrl": "http://{{.Values.loadBalancerAddress}}",
      "stage": "develop"
    }
kind: ConfigMap
metadata:
  name: app-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  labels:
    tenant: {{.Values.app.tenantPath}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
        context: tenant-artifacts
        tier: standard
        tenant: {{.Values.app.tenantPath}}
    spec:
      containers:
        - name: application
          image: {{.Values.app.application.image}}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: "http"
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/app/assets/config
      volumes:
        - name: config-volume
          configMap:
            name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: application-service
spec:
  selector:
    app: application
  ports:
    - name: http
      protocol: TCP
      port: {{.Values.app.application.port}}
      targetPort: {{.Values.app.application.targetPort}}
  type: NodePort
